services:
  server:
    image: scuda:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 14833:14833

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
